[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.155.2"

[[redirects]]
  from = "/*"
  to = "https://eifcom26.pages.dev/:splat"
  status = 301
  force = true
